/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package day2.app

import java.io.File


fun main() {
    val sub = Submarine()

    val fileContent = readFileDirectlyAsText("/Users/Alvin.Zhao/Projects/AoC/day2/app/src/main/resources/input")
    val resultProblem = sub.pilot(fileContent)
    println(resultProblem)
    val resultProblem2 = sub.pilot2(fileContent)
    println(resultProblem2)
}

fun readFileDirectlyAsText(fileName: String): String =
    File(fileName).readText(Charsets.UTF_8)